# THis is a Markdown Block

## this is sample code 

### this is third heading

In [2]:
print("this is a python block")

this is a python block


## Installing the required libraries

In [9]:
! pip install numpy

## Importing the required libraries

In [10]:
import numpy as np

initialise the array with the help of numpy

In [12]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [13]:
arr = arr * 2
print(arr)

[ 2  4  6  8 10]


In [14]:
arr.shape

(5,)

In [15]:
arr1 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr1)
arr1.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

In [17]:
arr

array([ 2,  4,  6,  8, 10])

In [16]:
arr[1]

np.int64(4)

In [18]:
arr[1:4]

array([4, 6, 8])

### Creating a 2-Dimentional Array

In [19]:
a = np.array([[1, 2, 3, 4, 5], [5, 6, 7, 8, 9], [6, 7, 8, 9, 10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [24]:
a.shape

(3, 5)

In [25]:
a.size


15

In [ ]:
## a[rows,columns] - rows and columns are indexed from 0
a[1,3]

np.int64(8)

In [23]:
a.ndim

2

Get a sub-matrix from [[2,3,4,5,6],[9,8,7,6,5]] 

In [26]:
normal_arr = np.array([[2, 3, 4, 5, 6],[9,8,7,6,5]])

In [27]:
normal_arr

array([[2, 3, 4, 5, 6],
       [9, 8, 7, 6, 5]])

In [30]:
sliced_arr = normal_arr[:,2:]
sliced_arr

array([[4, 5, 6],
       [7, 6, 5]])

In [31]:
zero_matrix = np.zeros((3,4))
zero_matrix


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
one_matrix = np.ones((3,4))
one_matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
empty_matrix = np.empty(2)
empty_matrix

array([0., 0.])

In [34]:
rangeOfNum= np.arange(10)
rangeOfNum

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
rangeWithStep = np.arange(0,10,2) ## Start, Stop, Step
rangeWithStep 

array([0, 2, 4, 6, 8])

In [ ]:
arr = np.array([5,2,1,3,7,6,8])
arr.sort() ## sorting in ascending order , sort() is combination of quick sort, merge sort and insertion sort, TimSort is used for sorting
arr

array([1, 2, 3, 5, 6, 7, 8])

In [44]:
arr1= np.array([1,2,3,4,5])
arr2 = np.array([5,6,7,8,9])

np.concatenate((arr1,arr2)) ## concatenating two arrays

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 9])

In [54]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [57]:
np.concatenate((x,y), axis=0) ## concatenating two arrays, it will concatenate along the first axis by default, if we want to concatenate along the second axis we can use axis=1

array([[1, 2],
       [3, 4],
       [5, 6]])